TARGET = libgpx-x
TEMPLATE = lib
CONFIG -= qt

DEFINES += GPX_BUILD

#static library build
CONFIG += static

HEADERS += \ 
    include/gpx/ext/UnorderedMap.hpp \
    include/gpx/ext/UnorderedSet.hpp \
    include/gpx/log/Log.hpp \
    include/gpx/log/LogBuf.hpp \
    include/gpx/log/LogStream.hpp \
    include/gpx/log/macros.hpp \
    include/gpx/math/basic/backend.hpp \
    include/gpx/math/basic/const_VectorPtr.hpp \
    include/gpx/math/basic/const_VectorPtr.imp.hpp \
    include/gpx/math/basic/Matrix.hpp \
    include/gpx/math/basic/Matrix.imp.hpp \
    include/gpx/math/basic/MatrixStorage.hpp \
    include/gpx/math/basic/MatrixStorage.imp.hpp \
    include/gpx/math/basic/NNSolver.hpp \
    include/gpx/math/basic/Solver.hpp \
    include/gpx/math/basic/Solver.imp.hpp \
    include/gpx/math/basic/VectorPtr.hpp \
    include/gpx/math/basic/VectorPtr.imp.hpp \
    include/gpx/math/basic/VectorPtrStorage.hpp \
    include/gpx/math/basic/VectorPtrStorage.imp.hpp \
    include/gpx/math/native/_base_const_VectorPtr.hpp \
    include/gpx/math/native/_base_const_VectorPtr.imp.hpp \
    include/gpx/math/native/_base_VectorPtr.hpp \
    include/gpx/math/native/const_VectorPtr.hpp \
    include/gpx/math/native/const_VectorPtr.imp.hpp \
    include/gpx/math/native/const_VectorPtr2.hpp \
    include/gpx/math/native/Vector.hpp \
    include/gpx/math/native/Vector2.hpp \
    include/gpx/math/native/VectorPtr2.hpp \
    include/gpx/math/tnt_jama/backend.hpp \
    include/gpx/math/tnt_jama/const_VectorPtr.hpp \
    include/gpx/math/tnt_jama/Matrix.hpp \
    include/gpx/math/tnt_jama/Solver.hpp \
    include/gpx/math/tnt_jama/Solver.imp.hpp \
    include/gpx/math/tnt_jama/Vector.hpp \
    include/gpx/math/tnt_jama/VectorPtr.hpp \
    include/gpx/math/constants.hpp \
    include/gpx/math/functions.hpp \
    include/gpx/math/Matrix.hpp \
    include/gpx/math/NNSolver.hpp \
    include/gpx/math/Solver.hpp \
    include/gpx/math/structures.hpp \
    include/gpx/math/Vector.hpp \
    include/gpx/model/_base_IndexedPoly.hpp \
    include/gpx/model/_base_IndexedPoly_Index.hpp \
    include/gpx/model/_base_IndexedPoly_Iterator.hpp \
    include/gpx/model/_base_UnindexedPoly.hpp \
    include/gpx/model/_Poly_warning.hpp \
    include/gpx/model/Element.hpp \
    include/gpx/model/FillData.hpp \
    include/gpx/model/functions.hpp \
    include/gpx/model/Poly.hpp \
    include/gpx/model/PolyComplex.hpp \
    include/gpx/model/PolyGroup.hpp \
    include/gpx/model/Segment.hpp \
    include/gpx/model/VertexData.hpp \
    include/gpx/utils/Array.hpp \
    include/gpx/utils/Conditional.hpp \
    include/gpx/utils/DoubleBuffer.hpp \
    include/gpx/utils/DoubleBufferController.hpp \
    include/gpx/utils/functions.hpp \
    include/gpx/utils/IDoubleBuffered.hpp \
    include/gpx/utils/IObserver.hpp \
    include/gpx/utils/NonCopyable.hpp \
    include/gpx/utils/Observable.hpp \
    include/gpx/utils/Singleton.hpp \
    include/gpx/log.hpp \
    include/gpx/math.hpp \
    include/gpx/model.hpp \
    include/gpx/platform.hpp \
    include/gpx/utils.hpp \
    include/tnt_jama/jama_cholesky.h \
    include/tnt_jama/jama_eig.h \
    include/tnt_jama/jama_lu.h \
    include/tnt_jama/jama_qr.h \
    include/tnt_jama/jama_svd.h \
    include/tnt_jama/tnt.h \
    include/tnt_jama/tnt_array1d.h \
    include/tnt_jama/tnt_array1d_utils.h \
    include/tnt_jama/tnt_array2d.h \
    include/tnt_jama/tnt_array2d_utils.h \
    include/tnt_jama/tnt_array3d.h \
    include/tnt_jama/tnt_array3d_utils.h \
    include/tnt_jama/tnt_cmat.h \
    include/tnt_jama/tnt_fortran_array1d.h \
    include/tnt_jama/tnt_fortran_array1d_utils.h \
    include/tnt_jama/tnt_fortran_array2d.h \
    include/tnt_jama/tnt_fortran_array2d_utils.h \
    include/tnt_jama/tnt_fortran_array3d.h \
    include/tnt_jama/tnt_fortran_array3d_utils.h \
    include/tnt_jama/tnt_i_refvec.h \
    include/tnt_jama/tnt_math_utils.h \
    include/tnt_jama/tnt_sparse_matrix_csr.h \
    include/tnt_jama/tnt_stopwatch.h \
    include/tnt_jama/tnt_subscript.h \
    include/tnt_jama/tnt_vec.h \
    include/tnt_jama/tnt_version.h \
    include/gpx/math/basic/base_const_Vector.imp.hpp \
    include/gpx/math/const_VectorRef.hpp \
    include/gpx/math/VectorRef.hpp \
    include/gpx/math/MatrixPrint.hpp \
    include/gpx/math/VectorPrint.hpp \
    include/gpx/math/const_VectorTrait.hpp \
    include/gpx/math/VectorTrait.hpp \
    include/gpx/math/basic/const_VectorTrait.hpp \
    include/gpx/math/basic/VectorTrait.hpp \
    include/gpx/model/SegmentPrint.hpp \
    include/gpx/math/Point.hpp \
    include/gpx/math/const_PointRef.hpp \
    include/gpx/math/PointRef.hpp \
    include/gpx/math/const_PointTrait.hpp \
    include/gpx/math/PointTrait.hpp \
    include/gpx/math/PointPrint.hpp \
    include/gpx/model/const_SegmentPtr.hpp \
    include/gpx/model/SegmentPtr.hpp \
    include/gpx/model/const_SegmentTrait.hpp \
    include/gpx/model/SegmentTrait.hpp \
    include/gpx/math/const_MatrixTrait.hpp \
    include/gpx/math/MatrixTrait.hpp \
    include/gpx/math/basic/const_MatrixTrait.hpp \
    include/gpx/math/basic/MatrixTrait.hpp \
    include/gpx/math/const_MatrixRef.hpp \
    include/gpx/math/MatrixRef.hpp \
    include/gpx/math/basic/Vector.hpp \
    include/gpx/math/basic/Vector.imp.hpp \
    include/gpx/math/basic/traits.hpp
